# Generated by Django 4.2.7 on 2024-04-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=45, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=45, verbose_name="Фамилия")),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
    ]
