# Generated by Django 4.2.7 on 2024-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pic"),
        ),
    ]
