# Generated by Django 4.2.7 on 2024-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_profile_delete_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="TRAP"),
            preserve_default=False,
        ),
    ]
