# Generated by Django 4.2.7 on 2024-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"verbose_name": "Контент", "verbose_name_plural": "Контенты"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["-created"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["order"],
                "verbose_name": "Модуль",
                "verbose_name_plural": "Модули",
            },
        ),
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="Ссылка"),
        ),
    ]
