# Generated by Django 4.2.7 on 2024-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_content_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="files", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="content",
            name="video",
            field=models.URLField(blank=True, null=True, verbose_name="Видео"),
        ),
    ]
