# Generated by Django 4.2.7 on 2024-04-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_alter_content_file_alter_content_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["-created"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                default="download_4.jpg", upload_to="images/", verbose_name="Картинка"
            ),
            preserve_default=False,
        ),
    ]
