# Generated by Django 4.2.7 on 2024-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_alter_lesson_options_lesson_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="images/", verbose_name="Картинка"
            ),
            preserve_default=False,
        ),
    ]
