# Generated by Django 4.2.7 on 2024-04-23 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0006_module_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
