# Generated by Django 4.2.7 on 2024-05-17 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0009_lesson_save"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="unsave",
            field=models.ManyToManyField(
                blank=True,
                related_name="unsave",
                to=settings.AUTH_USER_MODEL,
                verbose_name="RemovePlaylist",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="save",
            field=models.ManyToManyField(
                blank=True,
                related_name="save",
                to=settings.AUTH_USER_MODEL,
                verbose_name="AddPlaylist",
            ),
        ),
    ]
