# Generated by Django 4.2.7 on 2024-05-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0011_alter_lesson_save_alter_lesson_unsave"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="unsave",
        ),
    ]
