# Generated by Django 4.2.7 on 2024-05-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_remove_lesson_unsave"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="save",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="students",
        ),
    ]
