# Generated by Django 4.2.7 on 2024-05-18 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0013_remove_lesson_save_remove_lesson_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="lesson_joined",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ученики",
            ),
        ),
    ]
