# Generated by Django 4.2.7 on 2024-05-18 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0014_lesson_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="save",
            field=models.ManyToManyField(
                blank=True,
                related_name="save_playlist",
                to=settings.AUTH_USER_MODEL,
                verbose_name="AddPlaylist",
            ),
        ),
    ]
