# Generated by Django 4.2.7 on 2024-05-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0015_lesson_save"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="save",
        ),
    ]
