# Generated by Django 4.2.7 on 2024-06-03 16:59

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0016_remove_lesson_save"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="youtube",
            field=embed_video.fields.EmbedVideoField(
                default="https://www.youtube.com/watch?v=-AOPAqxAFJk"
            ),
            preserve_default=False,
        ),
    ]
