# Generated by Django 4.2.7 on 2024-06-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0018_lesson_save"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="save",
        ),
    ]
